// Generated by CoffeeScript 1.6.3
(function() {
  var add, config, halfCircle, letterC, letterR, paint, paper, quaterCircle, square, sub, svg, times;

  svg = Snap('#svg');

  svg.attr({
    width: 400,
    height: 400,
    xmlns: "http://www.w3.org/2000/svg"
  });

  paper = svg.paper;

  config = {
    width: 30
  };

  square = function(x) {
    return x * x;
  };

  add = function(pa, pb) {
    return {
      x: pa.x + pb.x,
      y: pa.y + pb.y
    };
  };

  sub = function(pa, pb) {
    return {
      x: pa.x - pb.x,
      y: pa.y - pb.y
    };
  };

  times = function(p, s) {
    return {
      x: p.x * s,
      y: p.y * s
    };
  };

  halfCircle = function(s, e) {
    var half, r;
    r = Math.sqrt(square(s.x - e.x) + square(s.y - e.y)) / 2;
    return half = paper.path("M" + s.x + " " + s.y + " A" + r + "," + r + " 0 0,0 " + e.x + " " + e.y);
  };

  quaterCircle = function(s, e) {
    var half, r;
    r = Math.sqrt((square(s.x - e.x) + square(s.y - e.y)) / 2);
    return half = paper.path("M" + s.x + " " + s.y + " A" + r + "," + r + " 0 0,1 " + e.x + " " + e.y);
  };

  letterC = function() {
    var A, B, C, D, E, delta, g, start, step;
    start = {
      x: 193,
      y: 160
    };
    delta = {
      x: 0,
      y: 30
    };
    step = times(delta, 2);
    A = add(start, delta);
    B = sub(start, delta);
    C = add(A, step);
    D = sub(B, step);
    E = add(C, step);
    g = paper.g();
    g.add(halfCircle(A, B));
    g.add(halfCircle(B, C));
    g.add(halfCircle(C, D));
    g.add(halfCircle(D, E));
    g.attr({
      stroke: "white",
      strokeWidth: config.width,
      fill: "none",
      strokeLinecap: "round"
    });
    return g;
  };

  letterR = function() {
    var center, end, g, r, start;
    center = {
      x: 340,
      y: 310
    };
    r = 70;
    start = {
      x: center.x - r,
      y: center.y
    };
    end = {
      x: center.x,
      y: center.y - r
    };
    g = paper.g();
    g.add(quaterCircle(start, end));
    g.attr({
      stroke: "white",
      strokeWidth: config.width,
      fill: "none",
      strokeLinecap: "round"
    });
    return g;
  };

  (paint = function() {
    var g, offset, shadow;
    offset = 8;
    shadow = svg.filter(Snap.filter.shadow(offset, offset, 0, '#000', 0.1));
    paper.circle(200, 200, 190).attr({
      fill: '#aaf',
      filter: shadow
    });
    g = paper.g();
    g.add(letterC().attr({
      filter: shadow
    }));
    return g.add(letterR().attr({
      filter: shadow
    }));
  })();

}).call(this);

/*
//@ sourceMappingURL=main.map
*/
