// Generated by CoffeeScript 1.6.3
(function() {
  var add, halfCircle, letterC, letterR, paper, square, sub, svg, times;

  svg = Snap('#svg');

  svg.attr({
    width: 400,
    height: 400
  });

  paper = svg.paper;

  paper.circle(200, 200, 200).attr({
    id: "bg"
  });

  square = function(x) {
    return x * x;
  };

  add = function(pa, pb) {
    return {
      x: pa.x + pb.x,
      y: pa.y + pb.y
    };
  };

  sub = function(pa, pb) {
    return {
      x: pa.x - pb.x,
      y: pa.y - pb.y
    };
  };

  times = function(p, s) {
    return {
      x: p.x * s,
      y: p.y * s
    };
  };

  halfCircle = function(s, e) {
    var half, r;
    r = Math.sqrt(square(s.x - e.x) + square(s.y - e.y)) / 2;
    half = paper.path("M" + s.x + " " + s.y + " A" + r + "," + r + " 0 0,0 " + e.x + " " + e.y);
    return half.attr({
      "class": "half"
    });
  };

  (letterC = function() {
    var A, B, C, D, E, delta, start, step;
    start = {
      x: 170,
      y: 150
    };
    delta = {
      x: 0,
      y: 24
    };
    step = times(delta, 2);
    A = add(start, delta);
    B = sub(start, delta);
    C = add(A, step);
    D = sub(B, step);
    E = add(C, step);
    halfCircle(A, B);
    halfCircle(B, C);
    halfCircle(C, D);
    return halfCircle(D, E);
  })();

  (letterR = function() {
    var A, B, C, D, E, delta, start, step;
    start = {
      x: 280,
      y: 260
    };
    delta = {
      x: 20,
      y: 0
    };
    step = times(delta, 2);
    A = add(start, delta);
    B = sub(start, delta);
    C = add(A, step);
    D = sub(B, step);
    E = add(C, step);
    halfCircle(A, B);
    halfCircle(B, C);
    return halfCircle(C, D);
  })();

}).call(this);

/*
//@ sourceMappingURL=main.map
*/
